// animes-app/src/components/SearchBar.jsx
import React from "react";

export default function SearchBar({ value, onChange }) {
  return (
    <input
      type="text"
      placeholder="Buscar anime..."
      value={value}
      onChange={(e) => onChange(e.target.value)}
      style={{
        padding: 10,
        width: "80%",
        maxWidth: 400,
        borderRadius: 6,
        border: "1px solid #ccc",
        marginBottom: 20,
      }}
    />
  );
}

// meal-app/src/components/SearchBar.svelte
<script>
  export let value = "";
  export let onSearch;
</script>

<div class="search-container">
  <input
    type="text"
    placeholder="Buscar receita..."
    bind:value
    on:input={() => onSearch(value)}
  />
</div>

<style>
  .search-container input {
    width: 100%;
    padding: 12px;
    font-size: 16px;
    border-radius: 8px;
    border: 1px solid #ccc;
  }
</style>
